/*
 * lib.rs
 *
 * DEEPWELL - Wikijump API provider and database manager
 * Copyright (C) 2019-2025 Wikijump Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

//! Library version of the deepwell crate.
//!
//! This exists only to enable integration test runners to run the deepwell
//! server. It should have the largely same modules as `main.rs`.

#[macro_use]
extern crate exn;

#[macro_use]
extern crate log;

#[macro_use]
extern crate futures;

#[macro_use]
extern crate serde;

#[macro_use]
extern crate str_macro;

#[macro_use]
mod macros;

// Auto-generated by sea-orm-cli
#[allow(unused_imports)]
mod models;

pub mod api;
pub mod config;
pub mod constants;
pub mod database;
pub mod endpoints;
pub mod hash;
pub mod info;
pub mod license;
pub mod locales;
pub mod redis;
pub mod services;
pub mod types;
pub mod utils;
