//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "audit_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub event_id: i64,
    #[sea_orm(column_type = "Text")]
    pub event_type: String,
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: TimeDateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub ip_address: String,
    pub user_id: Option<i64>,
    pub site_id: Option<i64>,
    pub page_id: Option<i64>,
    pub extra_id_1: Option<i64>,
    pub extra_id_2: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
