services:
  cache:
    build: valkey
    restart: always
    # You can add a volume for /data if you wish
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"

  deepwell:
    build:
      context: ../..
      dockerfile: install/dev/deepwell/Dockerfile
    ports:
      - "2747:2747"
    links:
      - cache
      - database
    environment:
      - "REDIS_URL=redis://cache"
    restart: always
    healthcheck:
      test: ["CMD", "wikijump-health-check"]
      interval: 120s
      timeout: 2s
      retries: 3
      start_period: 600s
      start_interval: 10s
    depends_on:
      cache:
        condition: service_healthy
      database:
        condition: service_healthy

  framerail:
    build:
      context: ../..
      dockerfile: install/dev/framerail/Dockerfile
    ports:
      - "3000:3000"
    links:
      - deepwell
    environment:
      - "DEEPWELL_HOST=deepwell"
    restart: always
    healthcheck:
      test: ["CMD", "wikijump-health-check"]
      interval: 120s
      timeout: 2s
      retries: 3
    depends_on:
      deepwell:
        condition: service_healthy

  wws:
    build:
      context: ../..
      dockerfile: install/dev/wws/Dockerfile
    ports:
      - "7000:7000"
    links:
      - deepwell
      - cache
    environment:
      - "ADDRESS=[::]:7000"
      - "DEEPWELL_URL=http://deepwell:2747"
      - "REDIS_URL=redis://cache"
    restart: always
    healthcheck:
      test: ["CMD", "wikijump-health-check"]
      interval: 120s
      timeout: 2s
      retries: 3
    depends_on:
      deepwell:
        condition: service_healthy
      cache:
        condition: service_healthy

  caddy:
    build:
      context: ../..
      dockerfile: install/dev/caddy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    links:
      - framerail
      - wws
    restart: always
    healthcheck:
      test: ["CMD", "wikijump-health-check"]
      interval: 30s
      timeout: 2s
      retries: 3
    depends_on:
      deepwell:
        condition: service_healthy
