[[procedure]]
name = "Deploy Dev"
description = "Automatically deploy Wikijump dev on push"
tags = ["wikijump"]

[[procedure.config.stage]]
name = "Pull Wikijump"
enabled = true
executions = [
    { execution.type = "BatchPullRepo", execution.params.pattern = "wikijump-dev", enabled = true },
]

# TODO temporarily disable resource syncs until a long-term decision on managing these is decided
[[procedure.config.stage]]
name = "Update Infrastructure"
enabled = false
executions = [
    { execution.type = "RunSync", execution.params.sync = "wikijump-dev", enabled = false },
]

[[procedure.config.stage]]
name = "Deploy Stacks"
enabled = true
executions = [
    { execution.type = "BatchDeployStack", execution.params.pattern = "wikijump-dev, *-alerter", enabled = true },
]
