[[resource_sync]]
name = "wikijump-dev"
description = "Synchronizes infrastructure changes, as defined in TOML files in Wikijump source."
tags = ["wikijump", "system"]

[resource_sync.config]
linked_repo = "wikijump-dev"
resource_path = ["install/dev/komodo/"]
delete = true
webhook_enabled = false
include_user_groups = true
