name: '[backend] Docker build Minio (TEST)'

on:
  push:
    branches:
      - develop
    paths:
      - 'install/local/minio/*'
      - '.github/workflows/docker-build-minio.local.yaml'
      - '.github/workflows/docker-push-minio.local.yaml'

env:
  IMAGE_NAME: wikijump/minio
  DESCRIPTION: Modified version of Minio for integration testing
  NAME: caddy
  TIER: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: docker build --tag ${{ env.IMAGE_NAME }}:${{ env.TIER }} -f install/local/${{ env.NAME }}/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1

      - name: Push image to ECR
        if: github.ref == 'refs/heads/develop'
        uses: jwalton/gh-ecr-push@v2
        with:
          access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY }}
          secret-access-key: ${{ secrets.AWS_ECR_SECRET_KEY }}
          region: us-east-2
          local-image: ${{ env.IMAGE_NAME }}:${{ env.TIER }}
          image: ${{ env.IMAGE_NAME }}:${{ env.TIER }}
