name: '[backend] Docker build router (local)'

on:
  pull_request:
    paths:
      - 'deepwell/**'
      - 'install/local/router/Dockerfile'
      - '.github/workflows/docker-build-router.local.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -f install/local/router/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1
